"""Compare the static part of the engine with the scripts and write ``validation/report.md``.

    python validation/run_validation.py
"""

from __future__ import annotations

import sys
import time
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from piperom.inputs import AnalysisSettings, load_system  # noqa: E402
from piperom.sdof import derive_sdof  # noqa: E402
from validation.legacy import (ARCHETYPES, EQUIV_STATIC_EXAMPLE, archetype, compare_inputs,  # noqa: E402
                               compare_pushover, extract_support_displacements, procedure_settings,
                               procedure_static, script_sdof)

OUT = Path(__file__).resolve().parent / "report.md"


def main() -> None:
    lines = ["# Validation of `piperom` against the scripts", "",
             "Generated by `python validation/run_validation.py`. Paths of the scripts are relative to "
             "`code implementation for paper/`; the reference is their state in this commit (c13ed81 and the corrections of 2026-10-09, `docs/legacy_issues.md` E5–E6).", ""]

    # ------------------------------------------------------------------ 1. inputs
    lines += ["## 1. Archetype inputs vs the pushover drivers", "",
              "`inputs/archetypes/<tag>.yaml` against the arguments `Pushover2D/CS_Lumped_Iter_<tag>_cont_PO.py` "
              "passes to `iterate_shape_from_static` (geometry, pipe, braces, branches, lumped mains).", "",
              "| Archetype | Differences |", "|---|---|"]
    for tag in ARCHETYPES:
        diffs = compare_inputs(tag)
        lines.append(f"| {tag} | {'none' if not diffs else '; '.join(diffs)} |")
        print(f"inputs {tag}: {diffs or 'same'}")

    # ------------------------------------------------------------------ 2. pushover
    lines += ["", "## 2. Adaptive pseudo-pushover vs `Pushover2D/pushover_results_*.txt`", "",
              "Engine with the default settings. The reference files store values with 3 decimals; a value "
              "matches if the engine's value formatted with 3 decimals is identical.", "",
              "| Archetype | Values | Differing | Max abs. difference | Run time (s) |", "|---|---|---|---|---|"]
    for tag in ARCHETYPES:
        t = time.time()
        cmp = compare_pushover(tag)
        lines.append(f"| {tag} | {cmp['n_cells']} | {cmp['n_diff']} | {cmp['max_abs_diff']:.2e} | "
                     f"{time.time() - t:.1f} |")
        print(f"pushover {tag}: {cmp['n_diff']} differing of {cmp['n_cells']}")

    # ------------------------------------------------------------------ 3. SDOF
    lines += ["", "## 3. Equivalent SDOF vs `Pushover_SDOF/sdof_from_2d.py`", "",
              "`derive_sdof` with the default settings (Δc = pushover step closest to 12 mm, values rounded to 3 "
              "decimals as written in the pushover results) against `load_sdof_params(tag, 12.0)`. A row matches "
              "if Δc, Γ, M_eff and every spring's φ and scale are identical. Spring scale = trapezes represented by "
              "each SDOF spring (mains on the brace's side of x_center; α·n_braces for a branch).", "",
              "| Archetype | Δc (mm) | Γ engine / script | M_eff engine / script (t) | Identical | "
              "Transverse scales | Longitudinal scales |", "|---|---|---|---|---|---|---|"]
    settings = AnalysisSettings.from_dict()
    for tag in ARCHETYPES:
        ref = script_sdof(tag)
        p = derive_sdof(archetype(tag), settings)
        T = [(s.phi, s.n_trapezes) for s in p.supports if s.kind == "transverse"]
        L = [(s.phi, s.n_trapezes) for s in p.supports if s.kind == "longitudinal"]
        same = (T == [tuple(v) for v in ref["trans"]] and L == [tuple(v) for v in ref["long"]]
                and (p.delta_c, p.gamma, p.effective_mass) == (ref["dc"], ref["Gamma"], ref["mass"]))
        lines.append(f"| {tag} | {p.delta_c:.3f} | {p.gamma:.3f} / {ref['Gamma']:.3f} | "
                     f"{p.effective_mass:.3f} / {ref['mass']:.3f} | {'yes' if same else 'NO'} | "
                     f"{[b for _, b in T]} | {[b for _, b in L]} |")
        print(f"sdof {tag}: {'match' if same else 'DIFFER'}")

    # ------------------------------------------------------------------ 4. proposed procedure
    ref = procedure_static()
    system = load_system(EQUIV_STATIC_EXAMPLE)
    p = derive_sdof(system, procedure_settings(round_decimals=None), float(ref["dc"]))
    shape_ref = extract_support_displacements(ref["d_norm"], ref["stiff_mask"], int(ref["nOrth"]))
    rel = lambda a, b: abs(a - b) / abs(b)  # noqa: E731
    lines += ["", "## 4. Proposed procedure: `code_proposed_procedure/equivalent_static.py`", "",
              f"Its stored output (`Results/EquivStatic/equiv_static_nT4_nL3.npz`, full precision, "
              f"Delta_c = {float(ref['dc']):g} mm) against `derive_sdof` on "
              "`inputs/examples/equivalent_static_example.yaml` (braces given as `count: 4`), SDOF at exactly Delta_c "
              "and at full precision (`round_decimals: null`).", "",
              "| Quantity | Script | Engine | Relative difference |", "|---|---|---|---|",
              f"| Gamma | {float(ref['Gamma']):.10f} | {p.gamma:.10f} | {rel(p.gamma, float(ref['Gamma'])):.1e} |",
              f"| Effective mass (t) | {float(ref['M_eff']):.10f} | {p.effective_mass:.10f} | "
              f"{rel(p.effective_mass, float(ref['M_eff'])):.1e} |",
              f"| u_SDOF (mm) | {float(ref['u_sdof']):.10f} | {p.u_sdof:.10f} | {rel(p.u_sdof, float(ref['u_sdof'])):.1e} |",
              f"| Support shape (max abs. diff.) | {np.round(shape_ref, 4).tolist()} | "
              f"{np.round(p.support_shape, 4).tolist()} | {np.abs(p.support_shape - shape_ref).max():.1e} |",
              f"| Brace mask | {ref['stiff_mask'].tolist()} | {system.resolve().brace_mask.tolist()} | |"]

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
